# Generated by Django 3.1.7 on 2021-02-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='tipodocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField(verbose_name='')),
                ('idTipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tipodocumento')),
                ('lugarResidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.ciudad')),
            ],
        ),
    ]
